### ISSUE TITLE
hI I'M Coconut3510

### ISSUE THREAD

**Issue by Coconut3510** [gyuu-don/rgss-cs-club#1]
### first github activity since 2016 becaus Vincent Zheng (@DequaviousTheThird) is special and woke me up from my slumber and ended my github moratorium..
![image](https://user-images.githubusercontent.com/20586455/198356216-cb636796-fb66-417e-993c-9b2b6ce1c14e.png)

**Comment by AMwa1** [comment]
Wow very interesting thank you for the issue.

**Comment by AAR072** [comment]
Please don't randomly put issues.
